--------------------------------------------------------
--  File created - Thursday-September-20-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FRIENDS
--------------------------------------------------------

  CREATE TABLE "FICHAELND"."FRIENDS" 
   (	"FRIENDSHIPID" NUMBER(*,0), 
	"FRIENDONE" NUMBER(*,0), 
	"FRIENDTWO" NUMBER(*,0), 
	"FRIENDLVL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "FICHAELND"."LOCATION" 
   (	"LOCATIONID" NUMBER(*,0), 
	"LOCATION" VARCHAR2(30 BYTE), 
	"COORDINATEY" NUMBER(*,0), 
	"COORDINATEX" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRADEOFFERS
--------------------------------------------------------

  CREATE TABLE "FICHAELND"."TRADEOFFERS" 
   (	"TRADEOFFERID" NUMBER(*,0), 
	"USERID" NUMBER(*,0), 
	"POKEMONTRADED" VARCHAR2(255 BYTE), 
	"POKEMONOFFERED" VARCHAR2(20 BYTE), 
	"AGREED" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRADES
--------------------------------------------------------

  CREATE TABLE "FICHAELND"."TRADES" 
   (	"TRADEID" NUMBER(*,0), 
	"FRIENDONE" NUMBER(*,0), 
	"FRIENDTWO" NUMBER(*,0), 
	"POKEMONONE" VARCHAR2(255 BYTE), 
	"POKEMONTWO" VARCHAR2(255 BYTE), 
	"STARDUSTCOST" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "FICHAELND"."USERS" 
   (	"USER_ID" NUMBER(*,0), 
	"TRAINERLVL" NUMBER(*,0), 
	"TEAM" VARCHAR2(255 BYTE), 
	"LOCATION" VARCHAR2(255 BYTE), 
	"USER_NAME" VARCHAR2(255 BYTE), 
	"FRIENDCODE" NUMBER(*,0), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PERSON
--------------------------------------------------------

   CREATE SEQUENCE  "FICHAELND"."SEQ_PERSON"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 10 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FICHAELND"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
REM INSERTING into FICHAELND.FRIENDS
SET DEFINE OFF;
REM INSERTING into FICHAELND.LOCATION
SET DEFINE OFF;
REM INSERTING into FICHAELND.TRADEOFFERS
SET DEFINE OFF;
Insert into FICHAELND.TRADEOFFERS (TRADEOFFERID,USERID,POKEMONTRADED,POKEMONOFFERED,AGREED) values (81,28,'pikachu','ditto','NO');
Insert into FICHAELND.TRADEOFFERS (TRADEOFFERID,USERID,POKEMONTRADED,POKEMONOFFERED,AGREED) values (84,12,'pikachu','ditto','NO');
REM INSERTING into FICHAELND.TRADES
SET DEFINE OFF;
Insert into FICHAELND.TRADES (TRADEID,FRIENDONE,FRIENDTWO,POKEMONONE,POKEMONTWO,STARDUSTCOST) values (24,11,12,'pikachu','charmander',100);
REM INSERTING into FICHAELND.USERS
SET DEFINE OFF;
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (81,15,'valor','new jersey','mike440',12213131,'michael123');
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (84,32,'valor','new york','trainer12',3421423,'michael123');
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (28,40,'mystic','new york','Mystic7',123334567,null);
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (59,32,'valor','new york','rick',32421424,null);
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (30,40,'valor','flushing ','visRock',224234,'michael123');
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (91,40,'valor','flushing','michael1233',324324234,'todayIS123$');
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (51,35,'valor','new york','mike5',324823643,null);
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (71,30,'valor','new york','trainer1',21412412,null);
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (11,39,'valor','college point','FIchaelND',122112112,null);
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (12,34,'instinct','college point','DaBason',103104105,null);
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (53,34,'valor','new york','team3',324223423,null);
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (55,34,'valor','college point','bob',421412424,null);
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (57,34,'valor','college point','heelsim',14124214,null);
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (66,30,'valor','college point','pokemasterholly',34234234,null);
Insert into FICHAELND.USERS (USER_ID,TRAINERLVL,TEAM,LOCATION,USER_NAME,FRIENDCODE,PASSWORD) values (74,21,'valor','brooklyn','red3',23424322,null);
--------------------------------------------------------
--  Constraints for Table TRADEOFFERS
--------------------------------------------------------

  ALTER TABLE "FICHAELND"."TRADEOFFERS" MODIFY ("AGREED" NOT NULL ENABLE);
  ALTER TABLE "FICHAELND"."TRADEOFFERS" MODIFY ("POKEMONTRADED" NOT NULL ENABLE);
  ALTER TABLE "FICHAELND"."TRADEOFFERS" MODIFY ("POKEMONOFFERED" NOT NULL ENABLE);
  ALTER TABLE "FICHAELND"."TRADEOFFERS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "FICHAELND"."TRADEOFFERS" ADD PRIMARY KEY ("TRADEOFFERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FICHAELND"."TRADEOFFERS" MODIFY ("TRADEOFFERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "FICHAELND"."USERS" ADD UNIQUE ("FRIENDCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FICHAELND"."USERS" ADD UNIQUE ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FICHAELND"."USERS" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FICHAELND"."USERS" MODIFY ("FRIENDCODE" NOT NULL ENABLE);
  ALTER TABLE "FICHAELND"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "FICHAELND"."USERS" MODIFY ("LOCATION" NOT NULL ENABLE);
  ALTER TABLE "FICHAELND"."USERS" MODIFY ("TEAM" NOT NULL ENABLE);
  ALTER TABLE "FICHAELND"."USERS" MODIFY ("TRAINERLVL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "FICHAELND"."LOCATION" ADD PRIMARY KEY ("LOCATIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FRIENDS
--------------------------------------------------------

  ALTER TABLE "FICHAELND"."FRIENDS" ADD PRIMARY KEY ("FRIENDSHIPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FICHAELND"."FRIENDS" MODIFY ("FRIENDSHIPID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRADES
--------------------------------------------------------

  ALTER TABLE "FICHAELND"."TRADES" ADD PRIMARY KEY ("TRADEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FICHAELND"."TRADES" MODIFY ("TRADEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FRIENDS
--------------------------------------------------------

  ALTER TABLE "FICHAELND"."FRIENDS" ADD CONSTRAINT "FK_FRIENDONE" FOREIGN KEY ("FRIENDONE")
	  REFERENCES "FICHAELND"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "FICHAELND"."FRIENDS" ADD CONSTRAINT "FK_FRIENDTWO" FOREIGN KEY ("FRIENDTWO")
	  REFERENCES "FICHAELND"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRADEOFFERS
--------------------------------------------------------

  ALTER TABLE "FICHAELND"."TRADEOFFERS" ADD CONSTRAINT "FK_FRIENDOFFER" FOREIGN KEY ("USERID")
	  REFERENCES "FICHAELND"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRADES
--------------------------------------------------------

  ALTER TABLE "FICHAELND"."TRADES" ADD CONSTRAINT "FK_FRIENDTRADEONE" FOREIGN KEY ("FRIENDONE")
	  REFERENCES "FICHAELND"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "FICHAELND"."TRADES" ADD CONSTRAINT "FK_FRIENDTRADETWO" FOREIGN KEY ("FRIENDTWO")
	  REFERENCES "FICHAELND"."USERS" ("USER_ID") ENABLE;
